### ISSUE TITLE
Logo Proposal for CookedRabbit

### ISSUE THREAD

**Issue by area55git** [thyams/CookedRabbit#4]
Hi, I'm a graphic designer and I like to collaborate with open source projects. Do you know that the graphic image of a project is very important? thinking about it I would like to design a logo for your Project CookedRabbit.

I will be pleased to collaborate with you.

**Comment by thyams** [comment]
Sure, take a stab at it :)

**Comment by area55git** [comment]
Perfect @thyams, I'll send you a proposal soon. I'm going to work on it

**Comment by area55git** [comment]
Do you have any suggestions or something in mind? to develop the sketches.

**Comment by thyams** [comment]
I was thinking of a black outline, sketch of a comic-style rabbit, breathing fire down on the ground with scorch marks.

https://www.binkybunny.com/Portals/0/activeforums_Attach/Bunny_Comic_1.jpg

**Comment by area55git** [comment]
Hi @thyams Do you like this proposal?

[![LOGO_PROPOSAL_FOR_COOKEDRABBIT_1.jpg](https://s33.postimg.cc/qbg4gymin/LOGO_PROPOSAL_FOR_COOKEDRABBIT_1.jpg)](https://postimg.cc/image/xenzwkry3/)

This proposal has all your suggestions: Black outlined, fun, has a rabbit and has fire. I think a very complete proposal.

**Comment by thyams** [comment]
I love it.

**Comment by area55git** [comment]
I am pleased that you like it, I will prepare the files in various formats to send them. I would like you to place them in a folder inside Repository, I will place the logo in the Readme folder to merge.

Any other request?

**Comment by area55git** [comment]
@thyams Would you like a color version?

**Comment by thyams** [comment]
I could use a color one to differentiate the newer NetCore one.

**Comment by thyams** [comment]
I also don't have a logo for my website / houseofcat.io

**Comment by area55git** [comment]
houseofcat has repository on github?

**Comment by thyams** [comment]
This is it, under my personal name. I am moving code to here over time.

**Comment by area55git** [comment]
Hi @thyams 

I am working on my github portfolio to increase my reputation, for me it would be ideal if your website had a github repository. additionally I send you a proposal of the logo in color and a version for icon or favicon.

[![LOGO_PROPOSAL_FOR_COOKEDRABBIT.jpg](https://s33.postimg.cc/g7qzuvnnj/LOGO_PROPOSAL_FOR_COOKEDRABBIT.jpg)](https://postimg.cc/image/cbdnyw2nv/)

**Comment by area55git** [comment]
In the same way I will work on your Houseofcat proposal so that you can place it in the readme folder.

**Comment by thyams** [comment]
my personal github "thyams" will be the houseofcat repository.  I won't be having two.

**Comment by area55git** [comment]
Hi @thyams What do you think about this?

[![LOGO_PROPOSAL_FOR_HOUSEof_CAT.jpg](https://s33.postimg.cc/41kso1ewv/LOGO_PROPOSAL_FOR_HOUSEof_CAT.jpg)](https://postimg.cc/image/ikrxpg81n/)

**Comment by thyams** [comment]
Dude, you are awesome! You crushed it.

**Comment by area55git** [comment]
This is my proposal for the Readme folder

[![LOGO_PROPOSAL_FOR_COOKEDRABBIT_readme.jpg](https://s33.postimg.cc/jfehb50db/LOGO_PROPOSAL_FOR_COOKEDRABBIT_readme.jpg)](https://postimg.cc/image/id4aslhjv/)

**Comment by area55git** [comment]
In what formats do you need the files?

**Comment by thyams** [comment]
Go for lossless format such as a png or bmp and svg if you can?

**Comment by area55git** [comment]
Yes, perfect in a couple of hours I send you a link in GDrive

**Comment by area55git** [comment]
PR #5

**Comment by area55git** [comment]
[![COOKEDRABBIT_1.jpg](https://s33.postimg.cc/g8pyewwm7/COOKEDRABBIT_1.jpg)](https://postimg.cc/image/p3qspflej/)


This image is in the link
